create_account/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('sign_up/', include('sign_up.urls')),
    
]

sign_up/urls.py
from django.urls import path
from django.http import HttpResponse
from . import views  
from django.conf import settings
from django.conf.urls.static import static

app_name = 'sign_up'

urlpatterns = [
    path('', views.signUp, name='signUp'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sign_up/models.py
from django.db import models

# Create your models here.
class Account(models.Model):
    first_name = models.CharField(max_length=100, null=False)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100, unique=True, null=False)
    password = models.CharField(max_length=100)
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    HOBBIES_CHOICES =(
        ('Music', 'Music'),
        ('Sports', 'Sports'),
        ('Tracel', 'Tracel'),
        ('Movies', 'Movies'),
    )
    hobbies = models.CharField(max_length=20, choices=HOBBIES_CHOICES)
    SOURCE_OF_INCOME_CHOICES = (
        ('Employed', 'Employed'),
        ('Student', 'Student'),
        ('Business', 'Business'),
        ('Others', 'Others'),
    )
    source_of_income = models.CharField(max_length=20, choices=SOURCE_OF_INCOME_CHOICES)
    income = models.PositiveIntegerField(default=20)
    profile_pic = models.ImageField(upload_to='Profile_pic/', blank=True)
    age = models.PositiveIntegerField(default=18)
    bio = models.TextField(default='')

create_account/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

sign_up/views.py
from django.shortcuts import render, redirect
from .models import Account
from django.http import HttpResponse

def signUp(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        gender = request.POST.get('gender')
        email = request.POST.get('email')

        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')

        hobbies = request.POST.getlist('hobbies')
        source_of_income = request.POST.get('source_of_income')
        income = request.POST.get('income')
        profile_pic = request.FILES.get('profile_pic')
        age = request.POST.get('age')
        bio = request.POST.get('bio')

        if password != confirm_password:
            return render(request, 'sign_up/register.html',{
                'error': "passwords do not match. Please enter the password again!"
                })

        Account.objects.create(
            first_name=first_name,
            last_name=last_name,
            gender=gender,
            email=email,
            password=password,
            hobbies=",".join(hobbies),
            source_of_income=source_of_income,
            income=income,
            profile_pic=profile_pic,
            age=age,
            bio=bio
        )

        return HttpResponse("success")

    return render(request, 'sign_up/register.html')

sign_up/templates/sign_up/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up Page</title>
</head>
<body>
    <h1>Create Account</h1>
    <form method='POST' action="" enctype="multipart/form-data">
        {% csrf_token %}
        {% if error %}
        <p style="color:red">{{ error }}</p>
        {% endif %}
        <table>
            <tr>
                <td>
                    <label for="first_name">First Name:</label><br>
                    <input type="text" name="first_name" id="first_name" required>
                </td>
                <td>
                    <label for="last_name">Last Name:</label><br>
                    <input type="text" name="last_name" id="last_name">
                </td>
            </tr>
            
            <tr>
                <td colspan="2">
                    <label for="email">Email:</label><br>
                    <input type="text" name="email" id="email" size="58">                   
                </td>
            </tr>

            <tr>
                <td>
                    <label for="password">Password:</label><br>
                    <input type="password" name="password" id="password">                   
                </td>
                <td>
                    <label for="confirm_password">Confirm Password:</label><br>
                    <input type="password" name="confirm_password" id="confirm_password" required>                   
                </td>
            </tr>
            
            <tr>
                <td>
                    <label for="gender">Gender:</label><br>
                    <input type="radio" name="gender" id="male" value='Male'>Male
                    <input type="radio" name="gender" id="female" value='Female'>Female
                </td>
                <td>
                    <label for="hobbies">Hobbies:</label><br>
                    <input type="checkbox" name="hobbies" id="male" value='Music'>Music
                    <input type="checkbox" name="hobbies" id="female" value='Sports'>Sports
                    <input type="checkbox" name="hobbies" id="female" value='Travel'>Travel
                    <input type="checkbox" name="hobbies" id="female" value='Movies'>Movies
                </td>
            </tr>
            
            <tr>
                <td>
                    <label for="source_of_income">Source of Income:</label><br>
                    <select name="source_of_income" id="source_of_income">
                        <option value="Employed">Employed</option>
                        <option value="Student">Student</option>
                        <option value="Business">Business</option>
                        <option value="Others">Others</option>
                    </select>                   
                </td>
                <td>
                    <label for="income">Income:</label><br>
                    <input type="range" id="income" name="income" min="0" max="100" value="20"
                        oninput="document.getElementById('incomeValue').textContent = this.value">
                    <span id="incomeValue">20</span>K                 
                </td>
            </tr>

            <tr>
                <td>
                    <label for="profile_pic">Upload Profile Pic:</label><br>
                    <input type="file" name="profile_pic" id="profile_pic" value="Choose File">
                </td>
                <td>
                    <label for="age">Age:</label><br>
                    <input type="number" name="age" id="age" value="18">
                </td>
            </tr>
                <td colspan="2">
                    <label for="bio">Bio:</label><br>
                    <textarea id="bio" name="bio" rows="5" cols="56" placeholder=""></textarea>

                </td>
            <tr>

            <tr>
                <td colspan="2">
                    <div style="display: flex; justify-content: flex-end;">
                        <button type="submit">Submit</button>
                    </div>
                </td>
            </tr>

        </table>



    </form>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Home Page</h1>
    <a href="{% url 'sign_up:signUp'%}">  <!-- signUp is name in  -->
        <button type='button'>
            Sign Up
        </button>
    </a>
</body>
</html>